name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    name: Build, fmt, clippy, test
    permissions:
      contents: read
      security-events: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "guard: no tracked files under dist/"
        run: |
          set -euo pipefail
          files=$(git ls-files dist || true)
          if [ -n "$files" ]; then
            echo "dist/ contains tracked files:" >&2
            echo "$files" | sed -n '1,50p' >&2
            exit 1
          fi
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install nightly toolchain (report-time)
        run: rustup toolchain install nightly --profile minimal --no-self-update
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: fmt (check)
        id: fmt
        continue-on-error: true
        run: cargo fmt --all -- --check

      - name: rustfmt patch (artifact)
        if: steps.fmt.outcome == 'failure'
        run: |
          cargo fmt --all
          git diff > rustfmt.patch || true
        shell: bash

      - name: Upload rustfmt.patch
        if: steps.fmt.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: rustfmt-patch
          path: rustfmt.patch

      - name: Fail on formatting
        if: steps.fmt.outcome == 'failure'
        run: |
          echo "Formatting issues detected. Download rustfmt-patch artifact to apply." >&2
          exit 1

      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: build
        run: cargo build --workspace --all-targets

      - name: Install coreutils (macOS)
        if: runner.os == 'macOS'
        run: brew install coreutils

      - name: validate commit messages (PR only)
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          set -euo pipefail
          BASE="origin/${GITHUB_BASE_REF}"
          git fetch origin "${GITHUB_BASE_REF}:${GITHUB_BASE_REF}" --depth=200 || true
          echo "Checking commit messages between $BASE..HEAD"
          bad=0
          while read -r subject; do
            # Allow merge and revert commits
            if [[ "$subject" =~ ^Merge\ .* || "$subject" =~ ^Revert\ .* ]]; then
              continue
            fi
            # Accept common Conventional Commit types (now including 'ci', 'release', and 'ci/tests'), and a longer subject (≤120)
            if [[ ! "$subject" =~ ^(feat|fix|chore|docs|test|refactor|ci|release|ci/tests)(\(.*\))?:\ .{1,120}$ ]]; then
              echo "Invalid commit subject: $subject" >&2
              bad=1
            fi
          done < <(git log --format=%s "$BASE"..HEAD)
          if [ "$bad" -ne 0 ]; then
            echo "warning: commit messages not compliant; NOT failing CI on PR" >&2
          fi

      - name: test (workspace, no-fail-fast)
        env:
          DEVIT_TIMEOUT_SECS: 300
        run: |
          set -euo pipefail
          TO=$(command -v timeout || command -v gtimeout || echo "")
          if [ -n "$TO" ]; then
            if ! "$TO" "300s" cargo +nightly test -p devit-tui -- --nocapture --report-time --test-threads=1; then
              echo "warn: --report-time unavailable; retrying devit-tui tests without it" >&2
              "$TO" "300s" cargo +nightly test -p devit-tui -- --nocapture --test-threads=1
            fi
            "$TO" "${DEVIT_TIMEOUT_SECS}s" cargo test --workspace --all-targets --no-fail-fast
          else
            echo "warn: no timeout available; running tests without external timeout" >&2
            if ! cargo +nightly test -p devit-tui -- --nocapture --report-time --test-threads=1; then
              echo "warn: --report-time unavailable; retrying devit-tui tests without it" >&2
              cargo +nightly test -p devit-tui -- --nocapture --test-threads=1
            fi
            cargo test --workspace --all-targets --no-fail-fast
          fi

      - name: Generate DevIt reports (SARIF/JUnit)
        run: |
          set -euo pipefail
          mkdir -p .devit/reports
          # Try to generate SARIF/JUnit via DevIt; tolerate failures and create stubs
          cargo run -p devit-cli --bin devit -- report sarif >/dev/null 2>&1 || true
          [ -s .devit/reports/sarif.json ] || echo '{"runs":[]}' > .devit/reports/sarif.json
          cargo run -p devit-cli --bin devit -- report junit >/dev/null 2>&1 || true
          if [ ! -s .devit/reports/junit.xml ]; then
            printf '%s\n' \
              '<?xml version="1.0" encoding="UTF-8"?>' \
              '<testsuites><testsuite name="ci" tests="0" failures="0"/></testsuites>' > .devit/reports/junit.xml
          fi
      - name: Generate SBOM (CycloneDX)
        run: |
          cargo run -p devit-cli --bin devit -- sbom gen --out .devit/sbom.cdx.json >/dev/null

      - name: Aggregate quality (thresholds)
        run: |
          set -euo pipefail
          mkdir -p .devit/reports
          # Use cargo run for portability across OS/matrices
          cargo run -p devit-cli --bin devit -- quality gate \
            --junit .devit/reports/junit.xml \
            --sarif .devit/reports/sarif.json \
            --json | tee .devit/reports/quality.json || true
          # Fallback minimal JSON to avoid breaking subsequent steps
          [ -s .devit/reports/quality.json ] || echo '{"payload":{"pass":false,"summary":{"tests_total":0,"tests_failed":0,"lint_errors":0,"lint_warnings":0}}}' > .devit/reports/quality.json

      - name: Upload DevIt reports + SBOM
        uses: actions/upload-artifact@v4
        with:
          name: devit-reports-${{ matrix.os }}
          path: |
            .devit/reports
            .devit/sbom.cdx.json

      - name: Make ensure_sarif executable
        run: chmod +x .devit/scripts/ensure_sarif.sh

      - name: Ensure SARIF (DevIt)
        run: .devit/scripts/ensure_sarif.sh .devit/reports/sarif.json

      - name: Upload SARIF (DevIt)
        if: ${{ always() && hashFiles('.devit/reports/sarif.json') != '' && github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .devit/reports/sarif.json
          category: devit-quality
          checkout_path: ${{ github.workspace }}
          wait-for-processing: true

      - name: PR comment (DevIt Quality Summary)
        if: always() && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p .devit/reports
          echo "### DevIt Quality Summary" > /tmp/devit_summary.md
          if [ ! -f .devit/reports/quality.json ]; then
            echo '{"payload":{"pass":false,"summary":{"tests_total":0,"tests_failed":0,"lint_errors":0,"lint_warnings":0}}}' > .devit/reports/quality.json
          fi
          jq -r '"- Tests: (.payload.summary.tests_failed)/(.payload.summary.tests_total) failed\n- Lint: (.payload.summary.lint_errors) errors, (.payload.summary.lint_warnings) warnings\n- Verdict: ((.payload.pass|tostring))"' .devit/reports/quality.json >> /tmp/devit_summary.md || true
          gh pr comment ${{ github.event.pull_request.number }} --body-file /tmp/devit_summary.md || true

      - name: Fail on thresholds (push only)
        if: github.event_name != 'pull_request'
        run: |
          jq -e '.payload.pass == true' .devit/reports/quality.json >/dev/null || exit 1

  tui_build:
    name: Build TUI binary
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build release TUI
        run: cargo build -p devit-tui --release
      - name: Upload devit-tui binary
        uses: actions/upload-artifact@v4
        with:
          name: devit-tui-linux-amd64
          path: target/release/devit-tui
          if-no-files-found: error

  vscode_pack:
    name: Package VS Code extension
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install extension dependencies
        run: npm install
        working-directory: editors/vscode/devit-vscode
      - name: Run ESLint
        run: npm run lint
        working-directory: editors/vscode/devit-vscode
      - name: Build extension
        run: npm run build
        working-directory: editors/vscode/devit-vscode
      - name: Package VSIX
        run: npx @vscode/vsce package --no-dependencies --out devit-vscode.vsix
        working-directory: editors/vscode/devit-vscode
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: devit-vscode-vsix
          path: editors/vscode/devit-vscode/devit-vscode.vsix
          if-no-files-found: error

  recipes_lint:
    name: Lint recipes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install recipe lint dependencies
        run: pip install yamllint pyyaml
      - name: yamllint recipes
        run: yamllint .devit/recipes
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Validate recipe schema
        run: |
          python - <<'PY'
          import sys
          import json
          from pathlib import Path
          import yaml

          root = Path('.devit/recipes')
          errors = []
          for path in sorted(root.glob('*.y*ml')):
              data = yaml.safe_load(path.read_text())
              if not isinstance(data, dict):
                  errors.append(f"{path}: expected mapping at root")
                  continue
              for field in ('id', 'name'):
                  if field not in data or not str(data[field]).strip():
                      errors.append(f"{path}: missing or empty '{field}'")
          if errors:
              print('\n'.join(errors), file=sys.stderr)
              sys.exit(1)
          PY
      - name: Parse recipes with devit CLI
        run: cargo run -p devit-cli --bin devit -- recipe list >/dev/null

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build release
        run: cargo build --release -p devit-cli --bin devit
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: devit-${{ matrix.os }}
          path: target/release/devit

  mcp_e2e:
    name: MCP E2E smoke
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build experimental bins
        run: cargo build -p devit-cli --features experimental --bins
      - name: Run E2E MCP
        run: |
          set -euo pipefail
          SRV="target/debug/devit-mcpd --yes --devit-bin target/debug/devit"
          ($SRV & echo $! > mcpd.pid)
          sleep 0.5
          target/debug/devit-mcp --cmd "$SRV" --policy >/dev/null
          target/debug/devit-mcp --cmd "$SRV" --call server.health --json '{}' >/dev/null
          target/debug/devit-mcp --cmd "$SRV" --call server.stats --json '{}' >/dev/null
          kill $(cat mcpd.pid) || true

  lint_meta:
    name: Lint meta (flags + errors)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install ripgrep
        run: |
          sudo apt-get update
          sudo apt-get install -y ripgrep
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Lint flags
        run: make lint-flags
      - name: Lint JSON errors shape
        run: scripts/lint_errors.sh
  mini_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --workspace
      - name: Run mini pipeline (verbose)
        run: |
          chmod +x scripts/mini_patch_pipeline_verbose.sh
          ./scripts/mini_patch_pipeline_verbose.sh
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devit-reports
          path: .devit/reports
